---
version: '2.0'
services:
  cloudflared:
    image: okn2015/cloudflared:v2
    expose:
      - port: 80
        as: 80
        to:
          - global: true
          - service: n8n
    env:
      - >-
        TUNNEL_1=tunnel token here (one for pg)
      - >-
        TUNNEL_2=tunnel token here (one for n8n)
  n8n:
    image: n8nio/n8n:latest
    expose:
      - port: 5678
        as: 5678
        to:
          - global: true
          - service: postgres
          - service: cloudflared
    env:
      - N8N_PORT=5678
      - N8N_SECURE_COOKIE=false
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_DATABASE=n8n
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_USER=postgres
      - DB_POSTGRESDB_PASSWORD=MNhASbKtgfJI1qsV
      - N8N_RUNNERS_ENABLED=true
      - HELLO=world
  postgres:
    image: postgres:latest
    expose:
      - port: 5432
        as: 5432
        proto: tcp
        to:
          - global: false
          - service: n8n
          - service: cloudflared
    command:
      - sh
      - '-c'
      - |
        mkdir -p /var/lib/postgresql/data/pgdata && \
        chown -R 999:999 /var/lib/postgresql/data/pgdata && \
        exec docker-entrypoint.sh postgres
    args:
      - ''
    env:
      - POSTGRES_PASSWORD=MNhASbKtgfJI1qsV
      - PGDATA=/var/lib/postgresql/pgdata
    params:
      storage:
        data:
          mount: '/var/lib/postgresql/data/pgdata '
          readOnly: false
profiles:
  compute:
    cloudflared:
      resources:
        cpu:
          units: 0.5
        memory:
          size: 1Gi
        storage:
          - size: 1Gi
    n8n:
      resources:
        cpu:
          units: 2
        memory:
          size: 2Gi
        storage:
          - size: 1Gi
    postgres:
      resources:
        cpu:
          units: 2
        memory:
          size: 2Gi
        storage:
          - size: 2Gi
          - name: data
            size: 10Gi
            attributes:
              persistent: true
              class: beta3
  placement:
    dcloud:
      pricing:
        cloudflared:
          denom: ibc/170C677610AC31DF0904FFE09CD3B5C657492170E7E52372E48756B71E56F2F1
          amount: 100000
        n8n:
          denom: ibc/170C677610AC31DF0904FFE09CD3B5C657492170E7E52372E48756B71E56F2F1
          amount: 100000
        postgres:
          denom: ibc/170C677610AC31DF0904FFE09CD3B5C657492170E7E52372E48756B71E56F2F1
          amount: 100000
deployment:
  cloudflared:
    dcloud:
      profile: cloudflared
      count: 1
  n8n:
    dcloud:
      profile: n8n
      count: 1
  postgres:
    dcloud:
      profile: postgres
      count: 1
