---
version: '2.0'
services:
  jenkins:
    image: okn2015/jenkins_cloudflared:vnext
    expose:
      - port: 80
        as: 80
        to:
          - global: true
          - service: agent1
    env:
      - >-
        TUNNEL_TOKEN=e
    params:
      storage:
        data:
          mount: /mnt/data
          readOnly: false
  agent1:
    image: okn2015/jenkins_ssh_agent_cloudflared:vnext1
    env:
      - JENKINS_AGENT_SSH_PUBKEY=
    expose:
      - port: 22
        as: 22
        proto: tcp
        to:
          - global: false
          - service: jenkins
    params:
      storage:
        data:
          mount: /home/jenkins
          readOnly: false
profiles:
  compute:
    jenkins:
      resources:
        cpu:
          units: 2
        memory:
          size: 2Gb
        storage:
          - size: 1Gi
          - name: data
            size: 10Gi
            attributes:
              persistent: true
              class: beta3
    agent1:
      resources:
        cpu:
          units: 4
        memory:
          size: 8Gi
        storage:
          - size: 1Gi
          - name: data
            size: 20Gi
            attributes:
              persistent: true
              class: beta3
  placement:
    dcloud:
      pricing:
        jenkins:
          denom: ibc/170C677610AC31DF0904FFE09CD3B5C657492170E7E52372E48756B71E56F2F1
          amount: 100000
        agent1:
          denom: ibc/170C677610AC31DF0904FFE09CD3B5C657492170E7E52372E48756B71E56F2F1
          amount: 100000
deployment:
  jenkins:
    dcloud:
      profile: jenkins
      count: 1
  agent1:
    dcloud:
      profile: agent1
      count: 1
